planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('shopping_list.urls'), name='shopping_list-urls'),
]

shopping_list/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.ListsOfList.as_view(), name='home'),
    path( '<slug:slug>/', views.list_detail, name='list_detail'),
    path( '<slug:slug>/edit_item/<int:item_id>',
        views.item_edit, name='item_edit'),
    path('<slug:slug>/delete_item/<int:item_id>',
        views.item_delete, name='item_delete'),
]

shopping_list/models.py
from django.db import models
from django.contrib.auth.models import User

PRIORITY = ((0, "Needed"), (1, "Will need soon"), (2, "Would be nice to have"), (3, "It can wait"))

# Create your models here.
class List(models.Model):
    list_name = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
    User, on_delete=models.CASCADE, related_name="shopping_list")
    
    def __str__(self):
        return f"{self.list_name}"

class Item(models.Model):
    list = models.ForeignKey(
        List, on_delete=models.CASCADE, related_name="items"
    )
    item_name = models.CharField(max_length=200, unique=False)
    min_quantity = models.IntegerField(default=0, blank=False)
    current_quantity = models.IntegerField(default=0, blank=False)
    priority = models.IntegerField(choices=PRIORITY, default=0)
    item_price = models.DecimalField(default=0, max_digits=6, decimal_places=2, blank=False)

    class Meta:
        ordering = ['-list', 'item_name',]

    def __str__(self):
        return f"{self.item_name}"

shopping_list/forms.py
from .models import Item
from django import forms


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('item_name','min_quantity', 'current_quantity', 'priority', 'item_price')

shopping_list/views.py
from django.shortcuts import render, get_object_or_404,reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import List, Item
from .forms import ItemForm

# Create your views here.

class ListsOfList(generic.ListView):
    queryset = List.objects.all()
    template_name = "shopping_list/index.html"
    paginate_by = 100


def list_detail(request, slug):

    queryset = List.objects.filter(slug=slug)
    list = get_object_or_404(queryset, slug=slug)
    items = Item.objects.filter(list=list)
    items_count = items.all().count()
    item_form = ItemForm
    if request.method == "POST":
        item_form = ItemForm(data=request.POST)
        if item_form.is_valid():
            item = item_form.save(commit=False)
            item.author = request.user
            item.list = list
            item.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Item added'
    )

    return render(
        request,
        "shopping_list/list_detail.html",
        {
            "list": list,
            "items": items,
            "items_count": items_count,
            "item_form": item_form,
        },
    )


def item_edit(request, slug, item_id):
    """
    view to edit items
    """
    if request.method == "POST":

        queryset = List.objects.all()
        list = get_object_or_404(queryset, slug=slug)
        item = get_object_or_404(Item, pk=item_id)
        item_form = ItemForm(data=request.POST, instance=item)

        if item_form.is_valid():
            item = item_form.save(commit=False)
            item.list = list
            item.save()
            messages.add_message(request, messages.SUCCESS, 'Item Updated!')
        else:
            messages.add_message(request, messages.ERROR, 'Error updating item!')

    return HttpResponseRedirect(reverse('list_detail', args=[slug]))


def item_delete(request, slug, item_id):
    """
    view to delete item
    """
    queryset = List.objects.all()
    list = get_object_or_404(queryset, slug=slug)
    item = get_object_or_404(Item, pk=item_id)

    item.delete()
    messages.add_message(request, messages.SUCCESS, 'Item deleted!')
    
    return HttpResponseRedirect(reverse('list_detail', args=[slug]))

shopping_list/templates/shopping_list/index.html
{% extends "base.html" %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Shopping List Entries Column -->
        <div class="col-12 custom-mt left">
            <div class="row">
                {% for list in list_list %}
                    {% if user.is_authenticated and list.author == user or list.author.username == "Admin" %}
                        <div class="col-md-4">
                            <div class="card mb-4">
                                <div class="card-body">
                                    <div class="image-container">
                                        <div class="image-flash">
                                            <a href="{% url 'list_detail' list.slug %}" class="list-item">
                                                <h2 class="list-name text-center">{{ list.list_name }}</h2>
                                            </a>
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

shopping_list/templates/shopping_list/list_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="list-title">{{ list.list_name }}
                    <strong class="basket-icon">
                        <!-- Displaying count of items -->
                        <i class="fas fa-shopping-basket"></i> {{ items_count }}
                    </strong>
                </h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="list-subtitle">{{ list.author }} created this list</p>
            </div>
        </div>
    </div>
</div>
</div>

<div class="container">
    <!-- Displaying Items -->
    <div class="row">
        <div class="col-md-8 custom-mb">
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each item in items -->
                {% for item in items %}
                <div class="list-item list-link">
                    <div id="item{{ item.id }}" class="item-name">
                        {{ item.item_name }}
                    </div>
                    <span class="item-span">{{ item.current_quantity }}/{{ item.min_quantity }}</span>
                    {% if user.is_authenticated %}
                    <button class="btn btn-edit" item_id="{{ item.id }}"><i class="btn-edit far fa-edit"
                            item_id="{{ item.id }}"></i></button>
                    <button class="btn btn-delete" item_id="{{ item.id }}"><i class="btn-delete fas fa-trash"
                            item_id="{{ item.id }}"></i></button>
                    {% endif %}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>

        <!-- Creating New Items -->
        <div class="col-md-4 card custom-mb mt-1">
            <div>
                {% if user.is_authenticated %}
                <h3>Add item</h3>
                <form id="itemForm" method="post">
                    {{ item_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Add</button>
                </form>
                {% else %}
                <p>Log in to add items</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete item?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
                btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extras %}
<script src="{% static 'js/items.js' %}"></script>
{% endblock extras%}

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}

<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <title>Planner</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Google Fonts CSS -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light maine-bg">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Shopping List<i
                    class="fas fas fa-shopping-cart cart-icon ms-3"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page"
                            href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <p class="text-center login-status">You are logged in as {{ user }}</p>
                    {% else %}
                    <p class="text-center login-status">You are not logged in</p>
                    {% endif %}
                </ul>
            </div>
        </div>


        <!-- displaying Django messages -->
        <div class="container">
            <div class="row">
                <div">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible
            fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </nav>

    <main class="flex-shrink-0 main-bg">

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Inspired by Code Instituters</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i>
        </p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>

    {% block extras %}
    {% endblock %}
    
</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}